spring:
  application:
    name: banking
  datasource:
    username: devuser
    password: devpassword
    url: jdbc:mysql://localhost:3307/dev_db?useUnicode=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379